service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

functions:
  cars:
    handler: app.app
    events:
      - http:
          path: cars
          method: get
  model:
    handler: app.app
    events:
    - http:
        path: model
        method: get

