service: aws-nodejs

provider:
  name: aws
  runtime: nodejs8.10

functions:
  cars:
    handler: app.hello
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

